name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Docker Tag (date only)
        run: echo "IMAGE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mariamwafik333/todo-app:${{ env.IMAGE_TAG }}

  scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set Docker Tag (date only)
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.19.0
        with:
          image-ref: mariamwafik333/todo-app:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0
          ignore-unfixed:
