name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t mariamwafik333/todo-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push mariamwafik333/todo-app:${{ github.sha }}

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.32.0
        with:
          image-ref: 'mariamwafik333/todo-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

