name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mariamwafik333/todo-app:latest

      # 🔐 Scan the Docker image using Trivy
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v0
        with:
          image-ref: mariamwafik333/todo-app:latest
          format: table
          exit-code: 0
          ignore-unfixed: true
